#!/usr/bin/env python3
"""Regenerate every RL result of the LESSER paper from the logged data in ``data/rl``.

This is the tier-1 reproduction: no GPU, no model weights and no training. It reads TensorBoard
scalars, saved selections and audit records, recomputes the reported numbers, and redraws the two RL
figures as vector PDFs. Each figure embeds its data payload in the PDF ``Subject`` field; the
payload matches the one embedded in the paper figure (compare with ``verify``).

Subcommands and the paper results they produce:

  corrupted  Figure 5 and Finding 3. Share of corrupted problems among the 128 problems selected from 512
             DAPO candidates (Qwen3-8B-Base, 64 responses each): LESSER 29.7% (38), full gradients 27.3%
             (35), AccGreedy 86.7% (111), Random 50% (64 expected).
  training   Figure 6 and Finding 4. Held-out Countdown accuracy over GRPO steps, two-seed means: step-50
             accuracy LESSER 32.46 and full gradients 32.46; LESSER reaches Random's final accuracy (29.79)
             at step 15, 70% fewer GRPO steps. Also the 11.8% Countdown share of the pool. LESSER uses
             the projected feature (64 x 128 two-sided sketch) in both figures.
  agreement  Appendix F.4 (RL statistics). First selection round: 1,835 of 5,120 problems with nonzero
             advantage; Spearman 0.69 between LESSER and full-gradient scores; the top 256 share 69% of
             their problems, Jaccard 0.53 against 0.075 for two random selections.
  all        Run the three subcommands, then compare both figure payloads and the RL numbers printed in
             the paper with ``data/rl/expected``; exits non-zero on any difference.
  verify     Compare the payload of a regenerated figure (PDF or JSON) with a reference payload (PDF or
             JSON); with two PDFs, also compare the drawn page content.

Example (from the repository root):

    python rl/figures.py all                       # writes outputs/rl/, exits non-zero on any mismatch
    python rl/figures.py verify outputs/rl/figure6_countdown_training.pdf <paper figure 6>.pdf

The RL cost numbers (FLOPs, feature storage and scoring wall clock of the cost table) are regenerated by
``python -m cost.rl_flops`` and ``python -m cost.timing_rl.parse_logs``.

Dependencies: numpy, reportlab (figures), tensorboard (event files), pypdf (``verify`` on PDFs only).
Missing or inconsistent inputs raise; nothing falls back to defaults.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
from pathlib import Path, PurePosixPath

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_ROOT = REPO_ROOT / "data" / "rl"
DEFAULT_OUT_DIR = REPO_ROOT / "outputs" / "rl"

# Paper colors (LESSER, full gradients, dynamic sampling, Random).
RL_METHOD_COLORS = dict(head="#C47A27", full="#506477", acc="#8A63B6", rand="#858A90")
EVAL_TAG = "val-core/countdown/reward/mean@16"  # verl in-training validation on countdown4_test
ARMS = [("prod", "LESSER", RL_METHOD_COLORS["head"], dict(marker="o", linestyle="-")),
        ("full", "Full policy gradient", RL_METHOD_COLORS["full"],
         dict(marker="s", linestyle="--", markerfacecolor="none")),
        ("acc", "Dynamic sampling", RL_METHOD_COLORS["acc"], dict(marker="^", linestyle="-")),
        ("rand", "Random", RL_METHOD_COLORS["rand"], dict(marker="D", linestyle=":"))]
COMPARISON_REQUIRED_STEPS = set(range(5, 31, 5))
SELECTION_INTERVAL, SELECTED_PER_ROUND = 10, 256
POOL_COUNTS = dict(countdown=4000, webinstruct=20000, dapo=10000)  # cdmix4
PRODUCER = "rl/figures.py"


# --------------------------------------------------------------------------------------------- helpers
def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def relative(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def require_file(path: Path) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"Missing input file: {path}")
    return path


def require_dir(path: Path) -> Path:
    if not path.is_dir():
        raise FileNotFoundError(f"Missing input directory: {path}")
    return path


def producer_record() -> dict:
    return dict(producer=PRODUCER, producer_sha256=sha256_bytes(Path(__file__).read_bytes()), command=sys.argv)


def write_json(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, indent=2, allow_nan=False) + "\n")


# --------------------------------------------------------------------------------------- vector figures
def draw_rl_vector_pdf(packet: dict, output: Path, *, noisy: bool = False) -> str:
    """Draw one of the paired main RL panels directly as PDF paths and text (paper Figures 5 and 6).

    No raster rendering or smoothing: the training panel connects the recorded seed means at their
    actual evaluation steps. Both panels share one canvas size, plot baseline and top edge. The packet
    is embedded as JSON in the PDF Subject field.
    """
    from reportlab.lib.colors import HexColor
    from reportlab.pdfgen import canvas

    if output.suffix != ".pdf":
        raise ValueError("The vector RL panel must be a PDF")
    width, height = 190.08, 145.44
    bottom, top = 32, 112
    pdf = canvas.Canvas(str(output), pagesize=(width, height), pageCompression=1, invariant=1)
    pdf.setAuthor("anonymous")
    pdf.setTitle("Corrupted share of selected problems" if noisy else "Countdown RL training")
    pdf.setSubject(json.dumps(packet, sort_keys=True))
    pdf.setLineCap(1)
    pdf.setLineJoin(1)

    def text(x, y, value, *, size=8.5, color="#405464", align="left"):
        pdf.setFillColor(HexColor(color))
        pdf.setFont("Helvetica", size)
        draw = {"left": pdf.drawString, "center": pdf.drawCentredString, "right": pdf.drawRightString}[align]
        draw(x, y, value)

    def line(x1, y1, x2, y2, *, color="#E8EDF1", weight=.5):
        pdf.setStrokeColor(HexColor(color))
        pdf.setLineWidth(weight)
        pdf.setDash()
        pdf.line(x1, y1, x2, y2)

    if noisy:
        # The axis runs to 110% so every value label sits after its bar and inside the axis range;
        # a white box behind each label keeps the 100% gridline from striking through it.
        left, right, axis_max = 62, 180, 110
        rows = packet["measurements"]["rows"]
        if len(rows) != 4:
            raise ValueError("The corrupted-reward panel requires four selectors")
        for tick in (0, 50, 100):
            x = left + (right - left) * tick / axis_max
            line(x, bottom, x, top)
            text(x, bottom - 13, str(tick), align="center")
        for index, row in enumerate(rows):
            value = row["corrupted_percent"]
            if not 0 < value <= 100:
                raise ValueError(f"Invalid corrupted share: {value}")
            y = top - (index + .5) * (top - bottom) / len(rows)
            text(left - 7, y - 3, row["label"], size=8, align="right")
            length = (right - left) * value / axis_max
            pdf.setFillColor(HexColor(RL_METHOD_COLORS[row["method"]]))
            pdf.roundRect(left, y - 5, length, 10, radius=2.5, stroke=0, fill=1)
            label = f"{value:.1f}"
            label_x, label_width = left + length + 5, pdf.stringWidth(label, "Helvetica", 9)
            if label_x + label_width > right:
                raise ValueError(f"Value label {label} would extend past the axis")
            pdf.setFillColor(HexColor("#FFFFFF"))
            pdf.rect(label_x - 1.5, y - 5.5, label_width + 3, 11, stroke=0, fill=1)
            text(label_x, y - 3, label, size=9, color="#1C2B37")
        line(left, bottom, right, bottom, color="#92A1AF", weight=.6)
        text((left + right) / 2, 6, "Corrupted share (%)", size=9, color="#1C2B37", align="center")
    else:
        left, right = 37, 183
        rows = packet["seed_averages"]["arms"]
        steps = packet["common_steps"]
        if set(rows) != {"prod", "full", "acc", "rand"} or len(steps) < 2:
            raise ValueError("The training panel requires four seed-averaged selectors")
        points = {key: {p["step"]: 100 * p["value"] for p in row["points"]} for key, row in rows.items()}
        values = [points[key][step] for key in rows for step in steps]
        lo, hi = 5 * np.floor(min(values) / 5), 5 * np.ceil(max(values) / 5)
        if hi <= lo:
            raise ValueError("Training curves must have a nonzero vertical range")
        xcoord = lambda step: left + (right - left) * (step - steps[0]) / (steps[-1] - steps[0])  # noqa: E731
        ycoord = lambda value: bottom + (top - bottom) * (value - lo) / (hi - lo)  # noqa: E731
        for tick in np.arange(lo, hi + .01, 10 if hi - lo >= 20 else 5):
            y = ycoord(tick)
            line(left, y, right, y)
            text(left - 6, y - 3, f"{tick:g}", align="right")
        for tick in steps:
            if tick % 10 == 0:
                x = xcoord(tick)
                line(x, bottom, x, bottom - 2, color="#92A1AF", weight=.6)
                text(x, bottom - 13, str(tick), align="center")
        line(left, bottom, right, bottom, color="#92A1AF", weight=.6)
        line(left, bottom, left, top, color="#92A1AF", weight=.6)
        text((left + right) / 2, 6, "GRPO training steps", size=9, color="#1C2B37", align="center")
        pdf.saveState()
        pdf.translate(9, (bottom + top) / 2)
        pdf.rotate(90)
        text(0, 0, "Test pass@1 (%)", size=9, color="#1C2B37", align="center")
        pdf.restoreState()
        styles = {"prod": (RL_METHOD_COLORS["head"], 1.8, ()),
                  "full": (RL_METHOD_COLORS["full"], 1.1, (4, 2.4)),
                  "acc": (RL_METHOD_COLORS["acc"], 1.3, ()),
                  "rand": (RL_METHOD_COLORS["rand"], 1.3, (1, 2.5))}
        for key in ("rand", "acc", "prod", "full"):
            color, weight, dash = styles[key]
            pdf.setStrokeColor(HexColor(color))
            pdf.setLineWidth(weight)
            pdf.setDash(dash)
            path = pdf.beginPath()
            path.moveTo(xcoord(steps[0]), ycoord(points[key][steps[0]]))
            for step in steps[1:]:
                path.lineTo(xcoord(step), ycoord(points[key][step]))
            pdf.drawPath(path)
            pdf.setDash()
        for index, key in enumerate(("prod", "full", "acc", "rand")):
            x, y = right - 80, bottom + 33 - index * 9.5  # the late-step curves leave this region empty
            color, weight, dash = styles[key]
            pdf.setStrokeColor(HexColor(color))
            pdf.setLineWidth(weight)
            pdf.setDash(dash)
            pdf.line(x, y, x + 10, y)
            pdf.setDash()
            label = rows[key]["label"].replace("Full policy gradient", "Full gradients")
            text(x + 14, y - 3, label, size=7.8, color="#1C2B37")
    pdf.showPage()
    pdf.save()
    return str(output)


# ------------------------------------------------------------------------------ Figure 5: corrupted
def read_jsonl_recorded(path: Path, root: Path, sources: list) -> list:
    payload = require_file(path).read_bytes()
    sources.append(dict(path=relative(path, root), sha256=sha256_bytes(payload)))
    return [json.loads(line) for line in payload.splitlines()]


def corrupted_measurements(pool: list, accuracies: dict, selections: dict) -> dict:
    """Corrupted shares of the saved LESSER and full-gradient selections, AccGreedy and Random.

    Rejects anything but the completed balanced 512-candidate pool with 64 responses per candidate.
    """
    labels = {}
    for row in pool:
        index, corrupted = row["extra_info"]["index"], row["extra_info"]["corrupted"]
        if type(index) is not int or type(corrupted) is not bool or index in labels:
            raise ValueError("Invalid or duplicate corrupted-pool record")
        labels[index] = corrupted
    if len(labels) != 512 or sum(labels.values()) != 256:
        raise ValueError("Expected the balanced 512-candidate pool with 256 corrupted problems")
    if set(accuracies) != {"head", "full"} or set(selections) != {"head", "full"}:
        raise ValueError("Both LESSER (head) and full-gradient records are required")
    rates = {}
    for method, rows in accuracies.items():
        rates[method] = {}
        for row in rows:
            index, total, correct = row["group_id"], row["total"], row["correct"]
            if (index not in labels or index in rates[method] or total != 64 or type(correct) is not int
                    or not 0 <= correct <= total or row["accuracy"] != correct / total):
                raise ValueError("Invalid, duplicate, or non-64-response reward record")
            rates[method][index] = correct / total
        if set(rates[method]) != set(labels):
            raise ValueError("Reward records do not cover every candidate")
    if rates["head"] != rates["full"]:
        raise ValueError("LESSER and full-gradient runs must score the same rollouts")
    measurements = []
    for method, label in (("head", "LESSER"), ("full", "Full gradients")):
        ids = [row["extra_info"]["index"] for row in selections[method]]
        if len(ids) != 128 or len(set(ids)) != 128 or not set(ids) <= set(labels):
            raise ValueError("Expected 128 distinct selected candidates")
        if any(row["extra_info"]["corrupted"] != labels[row["extra_info"]["index"]] for row in selections[method]):
            raise ValueError("Selected-set corruption labels differ from the pool")
        count = sum(labels[i] for i in ids)
        measurements.append(dict(method=method, label=label, selected_ids=ids, corrupted_count=count,
                                 corrupted_percent=100 * count / 128, kind="saved_selection"))
    # AccGreedy: the 128 mixed-reward candidates whose reward rate is closest to 0.5. The sort is stable,
    # so ties keep the order of the LESSER accuracy file.
    live = [row["group_id"] for row in accuracies["head"] if 0 < row["accuracy"] < 1]
    if len(live) < 128:
        raise ValueError("Fewer than 128 mixed-reward candidates for AccGreedy")
    greedy = sorted(live, key=lambda i: abs(rates["head"][i] - .5))[:128]
    count = sum(labels[i] for i in greedy)
    measurements.append(dict(method="acc", label="AccGreedy", selected_ids=greedy, corrupted_count=count,
                             corrupted_percent=100 * count / 128, kind="offline_selection"))
    measurements.append(dict(method="rand", label="Random", corrupted_percent=100 * sum(labels.values()) / len(labels),
                             kind="uniform_random_expectation"))
    return dict(candidates=len(labels), selected_per_method=128, responses_per_candidate=64,
                mixed_reward_candidates=len(live), rows=measurements)


def corrupted_packet(root: Path) -> dict:
    """Payload of Figure 5 from <root>/subpool/train.jsonl and <root>/{head,full}/ (LESSER, full gradients)."""
    root = require_dir(root)
    sources: list = []
    pool = read_jsonl_recorded(root / "subpool/train.jsonl", root, sources)
    accuracies = {m: read_jsonl_recorded(root / f"{m}/accuracy_by_problem.jsonl", root, sources)
                  for m in ("head", "full")}
    selections = {m: read_jsonl_recorded(root / f"{m}/selected/iter_0_{mode}_128/train.jsonl", root, sources)
                  for m, mode in (("head", "prod"), ("full", "sim"))}
    protocol = dict(setting="Scenario 1, local balanced DAPO subsample, initial selection only",
                    metric="Corrupted share of selected problems; lower is better",
                    accgreedy="Top 128 mixed-reward candidates closest to reward rate 0.5; ties retain head accuracy-file order",
                    random="Expected corrupted share under uniform selection from all 512 candidates",
                    uncertainty="One candidate subset and response draw; bars are descriptive, not confidence intervals",
                    figure_layout="half-page, paired RL figures", **producer_record())
    return dict(schema_version=1, measurements=corrupted_measurements(pool, accuracies, selections),
                protocol=protocol, sources=sources)


def corrupted_numbers(packet: dict) -> dict:
    rows = {row["method"]: row for row in packet["measurements"]["rows"]}
    return dict(
        candidates=packet["measurements"]["candidates"], selected=128, responses_per_candidate=64,
        mixed_reward_candidates=packet["measurements"]["mixed_reward_candidates"],
        corrupted_count={m: rows[m]["corrupted_count"] for m in ("head", "full", "acc")},
        corrupted_percent={m: rows[m]["corrupted_percent"] for m in ("head", "full", "acc", "rand")},
        random_expected_count=rows["rand"]["corrupted_percent"] / 100 * 128)


def run_corrupted(corrupted_root: Path, out_dir: Path) -> dict:
    packet = corrupted_packet(corrupted_root)
    pdf = out_dir / "figure5_corrupted_rewards.pdf"
    packet["figures"] = [pdf.name]
    draw_rl_vector_pdf(packet, pdf, noisy=True)
    write_json(out_dir / "figure5_corrupted_rewards.json", packet)
    numbers = corrupted_numbers(packet)
    c, p = numbers["corrupted_count"], numbers["corrupted_percent"]
    print("Figure 5 (corrupted rewards: Qwen3-8B-Base, 512 DAPO candidates, 256 corrupted, 64 responses, 128 selected)")
    print(f"  corrupted share: LESSER {p['head']:.1f}% ({c['head']}) | full gradients {p['full']:.1f}% ({c['full']}) | "
          f"AccGreedy {p['acc']:.1f}% ({c['acc']}) | Random {p['rand']:.1f}% ({numbers['random_expected_count']:g} expected)")
    print(f"  mixed-reward candidates: {numbers['mixed_reward_candidates']}; wrote {pdf}")
    return numbers


# -------------------------------------------------------------------------------- Figure 6: training
def load_events(directory: Path, root: Path, tag: str = EVAL_TAG) -> dict:
    """Read every event file of one run, keeping replayed evaluations and their provenance.

    A resumed run can log the same step twice; the evaluation with the latest wall time is kept, the
    others are listed as superseded, and two replays may not differ by more than two percentage points.
    """
    from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

    files = sorted(require_dir(directory).glob("events.out.tfevents.*"))
    if not files:
        raise FileNotFoundError(f"No event files in {directory}")
    points = []
    for path in files:
        acc = EventAccumulator(str(path), size_guidance={"scalars": 0}, purge_orphaned_data=False).Reload()
        if tag in acc.Tags()["scalars"]:
            points.extend(dict(step=e.step, value=e.value, wall_time=e.wall_time, source=path.name)
                          for e in acc.Scalars(tag))
    by_step, superseded = {}, []
    for point in sorted(points, key=lambda p: (p["wall_time"], p["source"])):
        previous = by_step.get(point["step"])
        if previous is not None:
            if abs(previous["value"] - point["value"]) > .02:
                raise ValueError(f"Replayed evaluation differs by over two points: {directory} step {point['step']}")
            superseded.append(previous)
        by_step[point["step"]] = point
    points = [by_step[k] for k in sorted(by_step)]
    if not points or any(p["step"] <= 0 or not np.isfinite(p["value"]) or not 0 <= p["value"] <= 1 for p in points):
        raise ValueError(f"Missing or invalid held-out evaluations: {directory}")
    return dict(points=points, superseded=superseded,
                sources=[dict(path=relative(p, root), bytes=p.stat().st_size, sha256=sha256_bytes(p.read_bytes()))
                         for p in files])


def average_runs(runs: list) -> dict:
    """Equal-weight mean over distinct training seeds at the evaluation steps every seed completed."""
    if not runs or len({run["seed"] for run in runs}) != len(runs):
        raise ValueError("Seed averages require nonempty runs with distinct seeds")
    by_seed = {}
    for run in runs:
        values = {p["step"]: p["value"] for p in run["points"]}
        if (not values or len(values) != len(run["points"])
                or any(s <= 0 or not np.isfinite(v) or not 0 <= v <= 1 for s, v in values.items())):
            raise ValueError("Each seed needs unique positive steps and finite accuracies in [0, 1]")
        by_seed[run["seed"]] = values
    common = sorted(set.intersection(*(set(v) for v in by_seed.values())))
    if len(common) < 2:
        raise ValueError("Seed averages require at least two shared evaluation steps")
    points = []
    for step in common:
        values = [v[step] for v in by_seed.values()]
        points.append(dict(step=step, value=float(np.mean(values)), n=len(values),
                           sample_std=float(np.std(values, ddof=1)) if len(values) > 1 else None,
                           values_by_seed={str(seed): v[step] for seed, v in by_seed.items()}))
    return dict(seeds=sorted(by_seed), points=points,
                excluded_steps_by_seed={str(seed): sorted(set(v) - set(common)) for seed, v in by_seed.items()})


def selection_shares(selections_root: Path) -> dict:
    """Countdown share of the 256 problems each arm selected per round (GradAlign Table 2 quantity)."""
    shares = {}
    for mode, _, _, _ in ARMS:
        rounds = {}
        for f in sorted(require_dir(selections_root / mode).glob("iter_*_256/train.jsonl")):
            r = int(f.parent.name.split("_")[1])
            counts: dict = {}
            payload = f.read_bytes()
            for line in payload.splitlines():
                src = json.loads(line)["data_source"]
                counts[src] = counts.get(src, 0) + 1
            if sum(counts.values()) != SELECTED_PER_ROUND or set(counts) - set(POOL_COUNTS):
                raise ValueError(f"Unexpected selected set in {f}: {counts}")
            rounds[r] = dict(step=SELECTION_INTERVAL * r, counts=counts,
                             countdown_share=counts.get("countdown", 0) / SELECTED_PER_ROUND,
                             path=relative(f, selections_root), sha256=sha256_bytes(payload))
        if not rounds or sorted(rounds) != list(range(len(rounds))):
            raise ValueError(f"Rounds must be contiguous from 0 for {mode}: {sorted(rounds)}")
        shares[mode] = [rounds[r] for r in sorted(rounds)]
    return dict(definition="Countdown share of the 256 problems selected at the start of each round; round r is selected at step 10r",
                pool_share=POOL_COUNTS["countdown"] / sum(POOL_COUNTS.values()), pool_counts=POOL_COUNTS,
                paper_reference=dict(label="GradAlign, paper Table 2 (own pool draw)", points=[[0, 92.9], [50, 62.1]]),
                per_arm=shares)


def training_packet(events_root: Path, selections_root: Path) -> dict:
    """Payload of Figure 6: seed-42 arms, seed-43 replicates, seed means, selection shares."""
    rows = {mode: dict(label=label, color=color, style=style, seed=42,
                       **load_events(events_root / "seed42" / mode, events_root))
            for mode, label, color, style in ARMS}
    comparisons = {}
    for mode, _, _, _ in ARMS:
        comparisons[mode + "_seed43"] = dict(label=rows[mode]["label"], color=rows[mode]["color"],
                                             style=rows[mode]["style"], seed=43,
                                             **load_events(events_root / "seed43" / mode, events_root))
    if any(not COMPARISON_REQUIRED_STEPS.issubset({p["step"] for p in row["points"]}) for row in comparisons.values()):
        raise ValueError("The comparison runs require every planned evaluation through step 30")
    display = {mode: dict(label=row["label"], color=row["color"], style=row["style"],
                          **average_runs([row, comparisons[mode + "_seed43"]]))
               for mode, row in rows.items()}
    common = sorted(set.intersection(*[{p["step"] for p in row["points"]} for row in display.values()]))
    if len(common) < 2:
        raise ValueError("At least two matched evaluation steps are required for a learning curve")
    runs_per_arm = {mode: len(row["seeds"]) for mode, row in display.items()}
    protocol = dict(task="GradAlign Scenario 2, local Countdown instance draw", model="Qwen2.5-Math-1.5B-Instruct",
                    evaluation_split="countdown4_test", evaluation_problems=500, evaluation_samples_per_problem=16,
                    metric_tag=EVAL_TAG, metric="Mean correctness over sampled responses; not pass@16",
                    head_feature="Advantage-weighted output-matrix gradient, two-sided 64 x 128 projection (GRADALIGN_PROD_SKETCH=1)",
                    training_runs_per_arm=runs_per_arm, display="Seed means at shared completed evaluation steps",
                    step_zero="Omitted: the available base measurement uses a different split",
                    status=f"Seed-averaged comparison available through step {common[-1]}",
                    replay_rule="Last wall-time evaluation per step from the resumed run; all superseded values retained; never average replays as independent seeds",
                    plotted_training_runs_per_arm=dict(runs_per_arm), figure_panels=["held_out_accuracy"],
                    figure_layout="half-page, paired RL figures", **producer_record())
    scope = "Head/full averaged over two seeds; shared 30-step horizon"
    return dict(
        schema_version=1, protocol=protocol, common_steps=common, arms=rows,
        seed_averages=dict(arms=display, common_steps=common,
                           rule="Equal-weight arithmetic mean over distinct training seeds at shared completed steps; no interpolation",
                           scope="; ".join(f"{row['label']}: seeds {', '.join(map(str, row['seeds']))}" for row in display.values())),
        selection_shares=selection_shares(selections_root),
        comparisons=dict(arms=comparisons, common_steps=sorted(COMPARISON_REQUIRED_STEPS),
                         exact_seed_means={key: display[key] for key in ("prod", "full")}, scope=scope))


def step_value(row: dict, step: int) -> float:
    """Accuracy in percent of one run or seed mean at one evaluation step."""
    return 100 * next(p for p in row["points"] if p["step"] == step)["value"]


def training_numbers(packet: dict) -> dict:
    """The Figure 6 numbers quoted in the paper, from the payload."""
    display = packet["seed_averages"]["arms"]
    steps, last = packet["common_steps"], packet["common_steps"][-1]
    random_final = step_value(display["rand"], last)
    first_reach = {mode: next((s for s in steps if step_value(row, s) >= random_final), None) for mode, row in display.items()}
    per_seed = {mode: {seed: 100 * v for seed, v in next(p for p in row["points"] if p["step"] == last)["values_by_seed"].items()}
                for mode, row in display.items()}
    return dict(final_step=last, final_mean={mode: step_value(row, last) for mode, row in display.items()},
                final_per_seed=per_seed,
                final_sample_std={mode: 100 * next(p for p in row["points"] if p["step"] == last)["sample_std"]
                                  for mode, row in display.items()},
                random_final=random_final, first_step_reaching_random_final=first_reach,
                fewer_steps_fraction=1 - first_reach["prod"] / last,
                pool_countdown_share=packet["selection_shares"]["pool_share"])


def run_training(out_dir: Path, events_root: Path, selections_root: Path) -> dict:
    packet = training_packet(events_root, selections_root)
    pdf = out_dir / "figure6_countdown_training.pdf"
    packet["figure"] = pdf.name
    draw_rl_vector_pdf(packet, pdf)
    write_json(out_dir / "figure6_countdown_training.json", packet)
    n = training_numbers(packet)
    f, s = n["final_mean"], n["final_per_seed"]
    names = dict(prod="LESSER", full="full gradients", acc="dynamic sampling", rand="Random")
    print(f"Figure 6 (Countdown, held-out countdown4_test, mean over 16 responses, two-seed means; steps {packet['common_steps']})")
    print(f"  step {n['final_step']}: " + " | ".join(f"{names[m]} {f[m]:.2f} (seeds 42/43: {s[m]['42']:.2f}/{s[m]['43']:.2f})"
                                                   for m in ("prod", "full", "acc", "rand")))
    reach = n["first_step_reaching_random_final"]
    print(f"  Random's final accuracy {n['random_final']:.2f} is first reached at step {reach['prod']} by LESSER, "
          f"{reach['full']} by full gradients, {reach['acc']} by dynamic sampling, {reach['rand']} by Random: "
          f"{100 * n['fewer_steps_fraction']:.0f}% fewer GRPO steps")
    print(f"  Countdown share of the pool: {POOL_COUNTS['countdown']:,} of {sum(POOL_COUNTS.values()):,} = "
          f"{100 * n['pool_countdown_share']:.1f}%")
    print(f"  wrote {pdf}")
    return n


# ---------------------------------------------------------------------------- Appendix F.4: agreement
def spearman(x: np.ndarray, y: np.ndarray) -> float:
    """Spearman rank correlation with average ranks for ties."""
    def rank(a):
        order = np.argsort(a, kind="stable")
        ranks = np.empty(len(a), dtype=np.float64)
        sorted_a = a[order]
        i = 0
        while i < len(a):
            j = i
            while j + 1 < len(a) and sorted_a[j + 1] == sorted_a[i]:
                j += 1
            ranks[order[i:j + 1]] = (i + j) / 2.0
            i = j + 1
        return ranks
    rx, ry = rank(np.asarray(x, dtype=np.float64)), rank(np.asarray(y, dtype=np.float64))
    return float(np.corrcoef(rx, ry)[0, 1])


def run_agreement(audit_files: list, accuracy_path: Path, out_dir: Path, selection_count: int = 256) -> dict:
    """LESSER versus full-gradient scores on every nonzero-advantage problem of the first round.

    Inputs: the base-policy audit records (data/rl/countdown/audit; the audit script is not distributed;
    the paper ran it as a 615-problem subset and its 1,220-problem complement, three shards each), which
    recomputes both cosines in FP32 from 16 responses per problem, and the round-0 accuracy file, which
    defines the nonzero-advantage problems. Top-k sets use a stable sort; ties do not occur in the paper data.
    """
    rows, meta = {}, []
    for path in audit_files:
        shard = json.loads(require_file(path).read_text())
        if not shard["complete"] or shard["n_done"] != len(shard["results"]):
            raise ValueError(f"Incomplete audit file {path}")
        meta.append((shard["n_live_groups"], shard["n_groups"], shard["mini_batch_size"]))
        for r in shard["results"]:
            if r["group_id"] in rows:
                raise ValueError(f"Group {r['group_id']} appears in two audit files")
            if r["n_responses"] != 16:
                raise ValueError("Every audited problem must have 16 responses")
            rows[r["group_id"]] = r
    if len(set(meta)) != 1:
        raise ValueError(f"Audit shards disagree on their population: {sorted(set(meta))}")
    n_live, n_groups, mbs = meta[0]
    accuracy = [json.loads(line) for line in require_file(accuracy_path).read_text().splitlines()]
    live = {r["group_id"] for r in accuracy if 0 < r["accuracy"] < 1}
    if len(accuracy) != n_groups or set(rows) != live or len(live) != n_live:
        raise ValueError("Audited problems must be exactly the nonzero-advantage problems of round 0")
    ids = sorted(rows)
    head = np.array([rows[g]["cos_head"] for g in ids])
    full = np.array([rows[g]["cos_full"] for g in ids])
    rho = spearman(head, full)
    top = lambda s: set(np.argsort(-s, kind="stable")[:selection_count].tolist())  # noqa: E731
    shared = len(top(head) & top(full))
    jaccard = shared / (2 * selection_count - shared)
    p = selection_count / len(ids)
    numbers = dict(candidates=n_groups, nonzero_advantage=len(ids), responses_per_problem=16, analysis_mini_batch=mbs,
                   spearman=rho, selection_count=selection_count, budget_fraction=p, shared=shared,
                   shared_fraction=shared / selection_count, jaccard=jaccard, random_jaccard=p / (2 - p))
    write_json(out_dir / "appendix_f4_rl_agreement.json", numbers)
    print("Appendix F.4, RL (first selection round, base policy, FP32 audit)")
    print(f"  problems with nonzero advantage: {len(ids):,} of {n_groups:,}")
    print(f"  Spearman correlation of LESSER and full-gradient scores: {rho:.3f}")
    print(f"  top {selection_count} ({100 * p:.0f}% of {len(ids):,}): {shared} shared = {100 * shared / selection_count:.1f}%, "
          f"Jaccard {jaccard:.3f}; two random selections p/(2-p) = {p / (2 - p):.3f}")
    return numbers


# ----------------------------------------------------------------------------------- verification
def payload_from(path: Path):
    """The figure payload of a PDF (Subject field) or a JSON manifest; None for a PDF without one."""
    if path.suffix == ".pdf":
        from pypdf import PdfReader
        metadata = PdfReader(str(require_file(path))).metadata or {}
        return json.loads(metadata["/Subject"]) if "/Subject" in metadata else None
    return json.loads(require_file(path).read_text())


def _tail(path: str, markers: set) -> str:
    parts = PurePosixPath(path).parts
    index = max(i for i, part in enumerate(parts) if part in markers)
    return "/".join(parts[index:])


EVENT_FILE_NAME = re.compile(r"(events\.out\.tfevents\.\d+)\.(.+)\.(\d+)\.(\d+)")


def event_file_name(name: str) -> str:
    """TensorBoard names event files events.out.tfevents.<time>.<host>.<pid>.<n>. The released copies
    in data/rl carry the host name ``node``; payloads are compared with every host name replaced by it."""
    match = EVENT_FILE_NAME.fullmatch(name)
    if match is None:
        raise ValueError(f"Not a TensorBoard event file name: {name}")
    return f"{match.group(1)}.node.{match.group(3)}.{match.group(4)}"


def normalize_payload(payload: dict) -> dict:
    """Drop producer, command and output locations; reduce input paths to their machine-independent tail.

    Event file names keep their time stamp, process id and counter; their host name becomes ``node``.
    """
    p = copy.deepcopy(payload)
    for key in ("figure", "figures"):
        p.pop(key, None)
    for key in ("producer", "producer_sha256", "command"):
        p.get("protocol", {}).pop(key, None)
    if "measurements" in p:  # Figure 5
        for source in p["sources"]:
            source["path"] = _tail(source["path"], {"subpool", "head", "full"})
        return p
    p.get("comparisons", {}).pop("figure", None)
    for row in list(p.get("arms", {}).values()) + list(p.get("comparisons", {}).get("arms", {}).values()):
        for source in row["sources"]:
            source["path"] = event_file_name(PurePosixPath(source["path"]).name)
        for point in row["points"] + row["superseded"]:
            point["source"] = event_file_name(point["source"])
    for rounds in p.get("selection_shares", {}).get("per_arm", {}).values():
        for entry in rounds:
            entry["path"] = "/".join(PurePosixPath(entry["path"]).parts[-3:])
    return p


def payload_differences(a, b, path="") -> list:
    if isinstance(a, dict) and isinstance(b, dict):
        out = []
        for key in sorted(set(a) | set(b)):
            if key not in a or key not in b:
                out.append(f"{path}/{key}: present in only one payload")
            else:
                out += payload_differences(a[key], b[key], f"{path}/{key}")
        return out
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        if len(a) != len(b):
            return [f"{path}: length {len(a)} != {len(b)}"]
        return [d for i, (x, y) in enumerate(zip(a, b)) for d in payload_differences(x, y, f"{path}[{i}]")]
    return [] if a == b else [f"{path}: {str(a)[:60]} != {str(b)[:60]}"]


def page_contents(path: Path) -> list:
    from pypdf import PdfReader
    return [page.get_contents().get_data() for page in PdfReader(str(path)).pages]


def verify(regenerated: Path, reference: Path) -> tuple:
    """Differences between two figures, and a description of what was compared.

    Payloads are compared after ``normalize_payload``. When both files are PDFs the drawn page content is
    compared too; a reference PDF whose metadata was stripped (as in the anonymized paper sources) is
    compared by page content only.
    """
    ours, theirs = payload_from(regenerated), payload_from(reference)
    if ours is None:
        raise ValueError(f"{regenerated} carries no payload; regenerate it with this script")
    differences, compared = [], []
    if theirs is not None:
        differences += payload_differences(normalize_payload(ours), normalize_payload(theirs))
        compared.append("payload")
    if regenerated.suffix == reference.suffix == ".pdf":
        if page_contents(regenerated) != page_contents(reference):
            differences.append("drawn page content differs")
        compared.append("drawn page content")
    if not compared:
        raise ValueError("Nothing to compare")
    return differences, " and ".join(compared)


def printed(value: float, template: str) -> str:
    """Round `value` the way the paper prints `template`: fixed decimals, or scientific such as 3.11e9."""
    if "e" in template:
        mantissa = template.split("e")[0]
        digits = len(mantissa.split(".")[1]) if "." in mantissa else 0
        m, e = f"{value:.{digits}e}".split("e")
        return f"{m}e{int(e)}"
    digits = len(template.split(".")[1]) if "." in template else 0
    return f"{value:.{digits}f}"


def paper_number_values(numbers: dict) -> dict:
    """Recomputed values under the keys of data/rl/expected/paper_numbers.json."""
    f5, f6, f4 = numbers["figure5"], numbers["figure6"], numbers["appendix_f4"]
    return {
        "figure5.lesser_corrupted_percent": f5["corrupted_percent"]["head"],
        "figure5.full_corrupted_percent": f5["corrupted_percent"]["full"],
        "figure5.accgreedy_corrupted_percent": f5["corrupted_percent"]["acc"],
        "figure5.random_corrupted_percent": f5["corrupted_percent"]["rand"],
        "figure5.lesser_corrupted_count": f5["corrupted_count"]["head"],
        "figure5.full_corrupted_count": f5["corrupted_count"]["full"],
        "figure5.accgreedy_corrupted_count": f5["corrupted_count"]["acc"],
        "figure5.random_expected_count": f5["random_expected_count"],
        "figure6.lesser_step50": f6["final_mean"]["prod"],
        "figure6.full_step50": f6["final_mean"]["full"],
        "figure6.random_step50": f6["final_mean"]["rand"],
        "figure6.lesser_first_step_at_random_final": f6["first_step_reaching_random_final"]["prod"],
        "figure6.fewer_steps_percent": 100 * f6["fewer_steps_fraction"],
        "figure6.pool_countdown_percent": 100 * f6["pool_countdown_share"],
        "appendix_f4.candidates": f4["candidates"],
        "appendix_f4.nonzero_advantage": f4["nonzero_advantage"],
        "appendix_f4.spearman": f4["spearman"],
        "appendix_f4.budget_percent": 100 * f4["budget_fraction"],
        "appendix_f4.shared_percent": 100 * f4["shared_fraction"],
        "appendix_f4.jaccard": f4["jaccard"],
        "appendix_f4.random_jaccard": f4["random_jaccard"],
    }


def run_all(args) -> int:
    args.out_dir.mkdir(parents=True, exist_ok=True)
    numbers = dict(figure5=run_corrupted(args.corrupted_root, args.out_dir))
    print()
    numbers["figure6"] = run_training(args.out_dir, args.events_root, args.selections_root)
    print()
    numbers["appendix_f4"] = run_agreement(args.audit_files, args.round0_accuracy, args.out_dir)
    write_json(args.out_dir / "rl_numbers.json", numbers)
    print()
    failures = 0
    for name, expected in (("figure5_corrupted_rewards", "figure5_payload.json"),
                           ("figure6_countdown_training", "figure6_payload.json")):
        diff, compared = verify(args.out_dir / f"{name}.pdf", require_file(args.data_root / "expected" / expected))
        print(f"{name}: {compared} {'identical to the paper figure' if not diff else 'DIFFERS from the paper figure'}")
        for line in diff[:20]:
            print("   ", line)
        failures += bool(diff)
    expected = json.loads(require_file(args.data_root / "expected" / "paper_numbers.json").read_text())
    expected.pop("_comment", None)
    values = paper_number_values(numbers)
    if set(values) != set(expected):
        raise ValueError(f"paper_numbers.json keys differ: {sorted(set(values) ^ set(expected))}")
    wrong = {key: (printed(values[key], text), text) for key, text in expected.items() if printed(values[key], text) != text}
    print(f"paper numbers: {len(expected) - len(wrong)} of {len(expected)} match the printed values")
    for key, (ours, theirs) in wrong.items():
        print(f"    {key}: {ours} != {theirs}")
    return 1 if failures or wrong else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["corrupted", "training", "agreement", "all", "verify"])
    ap.add_argument("paths", nargs="*", type=Path, help="verify: REGENERATED REFERENCE (PDF or JSON)")
    ap.add_argument("--data-root", type=Path, default=DEFAULT_DATA_ROOT)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    ap.add_argument("--corrupted-root", type=Path, default=None,
                    help="corrupted: <root>/subpool/train.jsonl and <root>/{head,full}/ (default <data-root>/corrupted)")
    ap.add_argument("--events-root", type=Path, default=None,
                    help="training: TensorBoard layout <root>/seed<S>/<arm>/ (default <data-root>/countdown/events)")
    ap.add_argument("--selections-root", type=Path, default=None,
                    help="training: seed-42 selections <root>/<arm>/iter_<r>_<mode>_256/train.jsonl")
    ap.add_argument("--audit-files", type=Path, nargs="+", default=None,
                    help="agreement: completed audit JSONs covering every nonzero-advantage problem (default: the six shards)")
    ap.add_argument("--round0-accuracy", type=Path, default=None,
                    help="agreement: accuracy_by_problem.jsonl of the audited round")
    args = ap.parse_args()
    args.corrupted_root = args.corrupted_root or args.data_root / "corrupted"
    args.events_root = args.events_root or args.data_root / "countdown" / "events"
    args.selections_root = args.selections_root or args.data_root / "countdown" / "selections" / "seed42"
    args.audit_files = args.audit_files or [args.data_root / "countdown" / "audit" / f"{part}_shard{k}of3.json"
                                            for part in ("subset", "remaining") for k in range(3)]
    args.round0_accuracy = args.round0_accuracy or args.data_root / "countdown" / "round0_seed42" / "accuracy_by_problem.jsonl"
    if args.command == "verify":
        if len(args.paths) != 2:
            ap.error("verify takes REGENERATED and REFERENCE")
        diff, compared = verify(*args.paths)
        print(f"{compared}: identical" if not diff else "\n".join(diff))
        return 1 if diff else 0
    if args.paths:
        ap.error("positional paths are only used by verify")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    if args.command == "all":
        return run_all(args)
    {"corrupted": lambda: run_corrupted(args.corrupted_root, args.out_dir),
     "training": lambda: run_training(args.out_dir, args.events_root, args.selections_root),
     "agreement": lambda: run_agreement(args.audit_files, args.round0_accuracy, args.out_dir)}[args.command]()
    return 0


if __name__ == "__main__":
    sys.exit(main())
